name: feedz
services:
  db:
    extends:
      file: compose.db.yaml
      service: mongo
    restart: unless-stopped
    ports:
      - "27020:27017"

  api:
    extends:
      file: compose.api.yaml
      service: nestjs
    build:
      context: ../api
      dockerfile: Dockerfile.local
    command: sh -c "cd /app/ && npm install && npm run start:dev"
    volumes:
      - ../api:/app
      - ../api/node_modules:/app/node_modules
    ports:
      - "3600:3600"

  crawler:
    extends:
      file: compose.crawler.yaml
      service: puppeteer
    build:
      context: ../crawler
      dockerfile: Dockerfile.local
    command: sh -c "cd /app/  && sh puppeteer.sh && pnpm install && pnpm run start:dev"
    volumes:
      - ../crawler:/app
      - ../crawler/node_modules:/app/node_modules

volumes:
  db-data:
    driver: local
